[package]
name = "sc-db-inspector"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "db-inspector"
path = "src/main.rs"

[dependencies]
clap = { workspace = true, features = ["derive"] }
codec = { workspace = true }
kvdb-rocksdb = { workspace = true }
sp-core = { workspace = true }
sp-database = { workspace = true, features = ["rocksdb"] }
sp-runtime = { workspace = true }
